name: Deploy Node.js Package
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  deploy-package:
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notification
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: deployment
          status: STARTED
          color: good
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@dexaga'
      - run: yarn
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Notify slack success
        if: success()
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: deployment
          status: SUCCESS
          color: good
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
      - name: Notify slack fail
        if: failure()
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: deployment
          status: FAILED
          color: danger
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
